### PR TITLE
Fix build on GHC < 8.4

### LINKED ISSUE #2: 0.2.0.1 doesn't build
The build fails with GHC 8.2 (and I believe all later releases) with,
```
  src/Control/Applicative/Interleaved.hs:68:13: error:
      Ambiguous occurrence ‘<>’
      It could refer to either ‘Sem.<>’,
                               imported from ‘Data.Semigroup’ at src/Control/Applicative/Interleaved.hs:30:1-28
                            or ‘Data.Monoid.<>’,
                               imported from ‘Data.Monoid’ at src/Control/Applicative/Interleaved.hs:32:1-31
     |
  68 |   mappend = (<>)
     |             ^^^^
```

### PR DESCRIPTION
**Pull request by bgamari**
This fixes #2, having been tested against GHC 8.0, 8.2, 8.4, and 8.6.

In addition, it adds Travis CI configuration; it would be good to enable this on the upstream project to ensure this sort of thing is caught earlier in the future.

Note, however, that due to #1 I have had to improvise the base commit from the 0.2.0.1 release tarball. You should rebase this on top of the actual released commit before merging.

### CODE REVIEW

**Comment by bgamari** [comment]
Ping.

**Comment by doaitse** [comment]
I just returned from a week away. I will look into things tomorrow, I am not a github expert, but it seems I have to become one.

Doaitse

**Comment by bgamari** [comment]
Thanks @doaitse!
